openapi: 3.0.0
info:
  version: 0.0.1
  title: Courts Document Downloader API
  description: Courts File Download API 
servers:
  - url: "http://localhost:8080"
tags:
  - name: Document Downloader API
paths:
  /document/upload:
    post:
      summary: File Tranfer Request
      tags:
        - File Transfer
      description: File Transfer Request
      requestBody:
        description: File transfer request
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/filetransfer_request"
      responses:
        '202':
          description: 'Accepted for processing'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/filetransfer_response"
  /document/status/{docId}:
   get:
      parameters:
        - in: path
          name: docId
          required: true
          schema:
            type: integer
            minimum: 1
          description: The document Id
      summary: Document status endpoint 
      tags: 
        - File Transfer
      description: File Transfer Status Request
      responses:
        '200':
          description: 'Status returned successfully'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/filetransferstatus_response"
  /ping:
   get:
      summary: Back end connectivity test
      tags: 
        - Utilities
      description: Back end connectivity test
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ping_response"
  /msgtest:
   post:
      summary: A MS Graph Test Operation. To be removed for prod. 
      tags: 
        - Test
      description: A MS Graph Test Operation. To be removed for prod
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/msgtest_request"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/test_response"
  /ordstest:
   post: 
      summary: ORDS put file Test Operation. To be removed for prod. 
      tags: 
        - Test
      description: ORDS put file Test Operation. To be removed for prod
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/filetransfer_request"
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ordsPush_response"               
components:
  schemas:
    filetransfer_request:
      type: object
      required:
          - objGuid
          - email
          - filePath
      properties:
        objGuid: 
           type: string
           format: byte
           description: 'An Object Guid as base64'
        email: 
           type: string
           format: email
           description: 'The recipients email address' 
        filePath:
           type: string
           description: 'The path to write the file to. Leave as null for writing to root.'
    filetransfer_response:
      type: object
      properties:
        objGuid: 
          type: string
        transferId:
          type: string
    filetransferstatus_response:
      type: object
      properties:
        percentTransfered:
          type: integer
        fileRequestedDtm: 
          type: string
          description: Creation date and time + UTC Offset 
          example: "2013-09-15T05:53:00-08:00"
        fileDeliveredDtm: 
          type: string
          description: Delivery date and time + UTC Offset 
          example: "2013-09-15T05:54:00-08:00"
        fileSize:
          type: integer
          format: int64
          description: File Size in bytes  
          example: "1223440"
        fileName: 
          type: string
          description: File name to be delivered 
        filePath: 
          type: string
          description: Expected file delivery path
        mime: 
          type: string
          description: File mime type
    ordsPush_response:
      type: object
      properties:
        filename:
          type: string
        mimetype: 
          type: string
    ping_response:
      type: string
    test_response:
      type: object
      properties:
        result:
          type: string
        error: 
          type: string
    msgtest_request:
      type: object
      required:
        - email
        - folder
        - fileName
        - data
      properties:
        email:
          type: string
          description: 'The email of the OneDrive user.'
        folder:
          type: string
          description: 'The OneDrive folder name to write the test file to.'
        fileName:
          type: string
          description: 'The name of the file to push with extension.'
        data: 
          type: string
          format: byte
          description: 'Base 64 encoded file data.'