#############################################################################################
###              Stage where Docker is building spring boot app using maven               ###
#############################################################################################
FROM maven:3.8.3-openjdk-17 as build

ARG SERVICE_NAME
ARG SKIP_TESTS=false

COPY . .

RUN mvn -B clean install \
        -P splunk \
        -Dmaven.test.skip=${SKIP_TESTS}

#############################################################################################
### Stage where Docker is running a java process to run a service built in previous stage ###
#############################################################################################
FROM eclipse-temurin:17-jre-alpine

# ARG MVN_PROFILES
ARG SERVICE_NAME

RUN apk update
RUN apk add busybox-extras
RUN apk --no-cache add curl

EXPOSE 8080

COPY --from=build ./target/${SERVICE_NAME}-*.jar /deployments/service.jar

#Adding certs to trusted certs java
USER root
COPY microsoft_graph.crt microsoft_graph.crt
COPY objectstore_gov_bc_ca.crt objectstore_gov_bc_ca.crt
COPY bccourtsca-my_sharepoint.crt bccourtsca-my_sharepoint.crt
RUN keytool -import -alias microsoftgraph -keystore $JAVA_HOME/lib/security/cacerts -file microsoft_graph.crt -storepass changeit -noprompt
RUN keytool -import -alias objectstoregovbcca -keystore $JAVA_HOME/lib/security/cacerts -file objectstore_gov_bc_ca.crt -storepass changeit -noprompt
RUN keytool -import -alias bccourtscamysharepoint -keystore $JAVA_HOME/lib/security/cacerts -file bccourtsca-my_sharepoint.crt -storepass changeit -noprompt

CMD ["java", "-jar", "/deployments/service.jar"]
#############################################################################################