
spring:
  application:
      name: DocDownloaderAPI
ords:
  endpoint: ${ORDS_ENDPOINT:http://localhost:8080}
  auth:
    password: ${ORDS_AUTH_PASSWORD:password}
    username: ${ORDS_AUTH_USER:user}
  app:
    id: ${ORDS_APP_ID:id}        
    pwd: ${ORDS_APP_PWD:pwd}
    ticketlifetime: ${ORDS_APP_TICKETLIFETIME:20}      
      