name: Build/Unit Tests

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
jobs:
  maven:
    name: Maven App Build and Test
    runs-on: ubuntu-latest
    env:
      ACTION_DEBUG: true

    steps:   
      
      # Setup Java Environment
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
          cache: maven

      - name: Checkout Repository
        uses: actions/checkout@v2

     # Run Maven Verify      
      - name: Build with Maven
        run: mvn -B install -P all --file src/backend/pom.xml

